# Generated by Django 5.0.6 on 2024-07-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_link_newsletter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="link",
            old_name="created",
            new_name="date_created",
        ),
        migrations.RenameField(
            model_name="link",
            old_name="updated",
            new_name="date_updated",
        ),
    ]
