# Generated by Django 5.0.6 on 2024-06-23 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_newsletter_link_newsletter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsletter",
            old_name="sent",
            new_name="date_sent",
        ),
    ]
