# Generated by Django 5.0.6 on 2024-06-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_rename_sent_newsletter_date_sent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsletter",
            old_name="send_success",
            new_name="mailout_success",
        ),
    ]
