# Generated by Django 5.0.6 on 2024-06-30 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_rename_send_success_newsletter_mailout_success"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsletter",
            name="mailout_success",
        ),
    ]
