# Generated by Django 5.0.7 on 2024-08-06 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_alter_category_subscribers_alter_feed_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="subscribers",
            field=models.ManyToManyField(
                default=(),
                related_name="subscribed_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="feed",
            name="type",
            field=models.CharField(
                choices=[("rss", "Rss")], default="rss", max_length=50
            ),
        ),
    ]
