# Generated by Django 5.0.8 on 2024-08-15 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0008_alter_category_subscribers_alter_feed_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedlink",
            old_name="selected",
            new_name="saved",
        ),
        migrations.AlterField(
            model_name="category",
            name="subscribers",
            field=models.ManyToManyField(
                default=(),
                related_name="subscribed_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="feed",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="feedlink",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
