# Generated by Django 5.0.7 on 2024-07-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authnz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscribe_new_categories",
            field=models.BooleanField(default=True),
        ),
    ]
