# Generated by Django 5.0.7 on 2024-08-03 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authnz", "0002_user_subscribe_new_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="subscribe_new_categories",
        ),
    ]
