# Generated by Django 5.0.6 on 2024-06-24 08:34

import authnz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authnz", "0003_alter_user_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="api_key",
            field=models.CharField(
                default=authnz.models.generate_api_key, max_length=40
            ),
        ),
    ]
